(module aslWeb/views/mascotLabView
  :d "Interactive Canonical Chameleon Mascot Architecture and Biological Scroll Morphing View"
  :x [viewMascotLab
      renderMascotLabView]
  :i [(asl-text/string :a s)
      (aslWeb/components/mascot :a mascot)])

(df viewMascotLab [] -> Str
  :d "Renders focused Canonical Mascot Architecture and Live 2-Stage Morphing Workbench"
  "<div class=\"min-h-screen bg-ground text-ink py-10 px-4 sm:px-6 lg:px-8\">\n"
  "  <div class=\"max-w-6xl mx-auto space-y-12\">\n"
  "    \n"
  "    <!-- Header -->\n"
  "    <div class=\"flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-line pb-8\">\n"
  "      <div>\n"
  "        <div class=\"inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-mono bg-signal/15 text-signal border border-signal/30 mb-3 font-semibold shadow-[0_0_12px_rgba(176,96,255,0.2)]\">\n"
  "          <span class=\"w-2 h-2 rounded-full bg-signal animate-pulse\"></span>\n"
  "          ASL MASCOT ARCHITECTURE · ACTIVE DEVELOPMENT\n"
  "        </div>\n"
  "        <h1 class=\"text-3xl sm:text-4xl font-extrabold tracking-tight text-ink font-sans neon-title-gradient\">\n"
  "          Векторный Маскот Хамелеон: Эталон и Переход\n"
  "        </h1>\n"
  "        <p class=\"mt-2 text-sm text-ink-2 max-w-3xl leading-relaxed font-sans\">\n"
  "          Фокусный результат разработки без промежуточного шума: канонический логотип в навбаре (<strong>A-01</strong>), расправленный цепкий хвост на неоновой кибер-лиане (<strong>U-03</strong>) и физически смоделированный двухстадийный переход (Unhook &rarr; Curl).\n"
  "        </p>\n"
  "      </div>\n"
  "      <div class=\"flex items-center gap-3 shrink-0\">\n"
  "        <a href=\"/\" class=\"inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-surface hover:bg-surface-2 border border-line text-ink text-xs font-mono font-semibold transition-colors shadow-sm\">\n"
  "          &larr; На Главную (Hero Vine)\n"
  "        </a>\n"
  "      </div>\n"
  "    </div>\n"
  "\n"
  "    <!-- 2 Master Cards: Folded Logo vs Unfolded Hero -->\n"
  "    <div class=\"grid grid-cols-1 md:grid-cols-2 gap-8\">\n"
  "      \n"
  "      <!-- CARD 1: CANONICAL FOLDED LOGO (A-01) -->\n"
  "      <div class=\"p-6 sm:p-8 rounded-2xl neon-card flex flex-col justify-between\">\n"
  "        <div>\n"
  "          <div class=\"flex items-center justify-between gap-3 mb-4\">\n"
  "            <span class=\"px-3 py-1 rounded-full text-xs font-mono font-bold bg-signal/20 text-signal border border-signal/40\">\n"
  "              КАНОНИЧЕСКИЙ ЭТАЛОН (A-01)\n"
  "            </span>\n"
  "            <span class=\"text-xs font-mono text-ink-3\">Docked / Navbar Logo</span>\n"
  "          </div>\n"
  "          <h3 class=\"text-xl font-bold text-ink font-sans mb-2\">Сложенный вид (Логотип)</h3>\n"
  "          <p class=\"text-xs text-ink-3 leading-relaxed mb-6\">\n"
  "            Утверждённый бренд-знак для навбара и фавикона. Лунный нижний контур (D-00), ядро-капля (D-03, +95&deg;), честное монотонное сужение 38.9px &rarr; 0px и одинарная центральная линия без нагромождения.\n"
  "          </p>\n"
  "        </div>\n"
  "        \n"
  "        <div class=\"w-full aspect-square max-w-[280px] mx-auto bg-ground/80 rounded-xl border border-line p-6 flex items-center justify-center relative overflow-hidden shadow-inner my-4\">\n"
  "          <img src=\"/mascot_canonical_logo.svg\" alt=\"Canonical A-01 Logo Mark\" class=\"w-full h-full object-contain filter drop-shadow-[0_0_18px_rgba(192,132,252,0.5)]\" />\n"
  "        </div>\n"
  "\n"
  "        <div class=\"grid grid-cols-2 gap-3 pt-4 border-t border-line text-xs font-mono\">\n"
  "          <div class=\"bg-surface/50 p-2.5 rounded-lg border border-line/60\">\n"
  "            <div class=\"text-ink-3 text-[10px]\">ГЕОМЕТРИЯ</div>\n"
  "            <div class=\"font-bold text-ink mt-0.5\">D-00 + D-03 (+95&deg;)</div>\n"
  "          </div>\n"
  "          <div class=\"bg-surface/50 p-2.5 rounded-lg border border-line/60\">\n"
  "            <div class=\"text-ink-3 text-[10px]\">СУЖЕНИЕ</div>\n"
  "            <div class=\"font-bold text-emerald-400 mt-0.5\">Монотонное (1 линия)</div>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- CARD 2: UNFOLDED HERO MASCOT (U-03) -->\n"
  "      <div class=\"p-6 sm:p-8 rounded-2xl neon-card flex flex-col justify-between border-emerald-500/30 shadow-[0_0_24px_rgba(16,185,129,0.12)]\">\n"
  "        <div>\n"
  "          <div class=\"flex items-center justify-between gap-3 mb-4\">\n"
  "            <span class=\"px-3 py-1 rounded-full text-xs font-mono font-bold bg-emerald-500/20 text-emerald-400 border border-emerald-500/40\">\n"
  "              РАСПРАВЛЕННЫЙ ВИД (U-03)\n"
  "            </span>\n"
  "            <span class=\"text-xs font-mono text-emerald-400/80\">Hero Vine Anchor</span>\n"
  "          </div>\n"
  "          <h3 class=\"text-xl font-bold text-ink font-sans mb-2\">Хвост на Кибер-Лиане</h3>\n"
  "          <p class=\"text-xs text-ink-3 leading-relaxed mb-6\">\n"
  "            Стартовое состояние в левом верхнем углу херо-секции. Плавный ниспадающий S-изгиб огибает изумрудный стебель лианы и фиксируется цепким завитком, сохраняя живую пластику и простор вокруг туловища.\n"
  "          </p>\n"
  "        </div>\n"
  "        \n"
  "        <div class=\"w-full aspect-square max-w-[280px] mx-auto bg-ground/80 rounded-xl border border-emerald-500/30 p-6 flex items-center justify-center relative overflow-hidden shadow-inner my-4\">\n"
  "          <div class=\"w-full h-full flex items-center justify-center\">\n"
  "            " (mascot/viewChameleon) "\n"
  "          </div>\n"
  "        </div>\n"
  "\n"
  "        <div class=\"grid grid-cols-2 gap-3 pt-4 border-t border-line text-xs font-mono\">\n"
  "          <div class=\"bg-surface/50 p-2.5 rounded-lg border border-line/60\">\n"
  "            <div class=\"text-ink-3 text-[10px]\">СОПРЯЖЕНИЕ</div>\n"
  "            <div class=\"font-bold text-ink mt-0.5\">G&sup2; непрерывность (p220)</div>\n"
  "          </div>\n"
  "          <div class=\"bg-surface/50 p-2.5 rounded-lg border border-line/60\">\n"
  "            <div class=\"text-ink-3 text-[10px]\">ФИКСАЦИЯ</div>\n"
  "            <div class=\"font-bold text-emerald-400 mt-0.5\">Органический обхват</div>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "    </div>\n"
  "\n"
  "    <!-- Interactive Real-Time Morphing Engine Workbench -->\n"
  "    <div class=\"p-6 sm:p-8 rounded-2xl neon-card space-y-6\">\n"
  "      <div class=\"flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-line pb-4\">\n"
  "        <div>\n"
  "          <h3 class=\"text-lg font-bold text-ink font-sans flex items-center gap-2\">\n"
  "            <span class=\"w-2.5 h-2.5 rounded-full bg-signal\"></span>\n"
  "            Интерактивный скролл-морфинг (Unhook &rarr; Curl)\n"
  "          </h3>\n"
  "          <p class=\"text-xs text-ink-3 mt-1 font-sans\">\n"
  "            Подвигайте ползунок прогресса для проверки гладкости двухстадийного биологического перегиба хвоста в реальном времени:\n"
  "          </p>\n"
  "        </div>\n"
  "        <div class=\"flex items-center gap-2 font-mono text-xs text-signal font-bold shrink-0 bg-signal/10 px-3 py-1.5 rounded-xl border border-signal/20\">\n"
  "          <span>Прогресс: </span>\n"
  "          <span id=\"mascot-lab-progress-val\">0% (U-03 Vine)</span>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Live Slider -->\n"
  "      <div class=\"space-y-2\">\n"
  "        <input type=\"range\" id=\"mascot-lab-slider\" min=\"0\" max=\"1\" step=\"0.01\" value=\"0\" oninput=\"window.scrubMascotLab(this.value)\" class=\"w-full h-2.5 bg-inset rounded-lg appearance-none cursor-pointer accent-signal\" />\n"
  "        <div class=\"flex justify-between text-[11px] font-mono text-ink-3\">\n"
  "          <span>t = 0.00 (Расправлен на лиане)</span>\n"
  "          <span>t = 0.35 (Освобождение зацепа)</span>\n"
  "          <span>t = 1.00 (Сложенный логотип)</span>\n"
  "        </div>\n"
  "      </div>\n"
  "\n"
  "      <!-- Live Canvas & Transition Strip -->\n"
  "      <div class=\"grid grid-cols-1 lg:grid-cols-12 gap-6 items-center pt-2\">\n"
  "        <div class=\"lg:col-span-5 flex justify-center\">\n"
  "          <div class=\"w-64 h-64 bg-ground/90 rounded-2xl border border-line p-4 flex items-center justify-center relative shadow-inner\">\n"
  "            <svg id=\"mascot-lab-interactive-svg\" viewBox=\"0 0 200 200\" class=\"w-full h-full\" fill=\"none\">\n"
  "              " (mascot/viewCyberLiana) "\n"
  "              <g id=\"mascot-lab-body\" transform=\"translate(10 32) scale(0.48) translate(-34 -4)\" stroke=\"#C084FC\" stroke-width=\"2.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"none\" filter=\"url(#asl-glow)\">\n"
  "                " (mascot/chameleonApertureIris) "\n"
  "                <g class=\"spiral-tail-and-spine\">\n"
  "                  <path id=\"mascot-lab-spine\" d=\"\" />\n"
  "                  <path id=\"mascot-lab-belly\" d=\"\" />\n"
  "                </g>\n"
  "              </g>\n"
  "            </svg>\n"
  "          </div>\n"
  "        </div>\n"
  "\n"
  "        <div class=\"lg:col-span-7 space-y-3\">\n"
  "          <h4 class=\"text-xs font-mono font-bold uppercase tracking-wider text-ink-2\">Этапы трансформации без пересечения контура:</h4>\n"
  "          <div class=\"space-y-2 text-xs font-sans text-ink-3 leading-relaxed\">\n"
  "            <div class=\"p-2.5 rounded-xl bg-surface/40 border border-line/60 flex items-start gap-2.5\">\n"
  "              <span class=\"px-1.5 py-0.5 rounded bg-signal/20 text-signal font-mono font-bold text-[10px]\">01</span>\n"
  "              <div><strong class=\"text-ink\">Расцепление лианы ($0 \le t \le 0.35$):</strong> Кончик хвоста плавно отпускает стебель лианы и выпрямляется в свободную дугу $R$. Перегиб через себя исключён.</div>\n"
  "            </div>\n"
  "            <div class=\"p-2.5 rounded-xl bg-surface/40 border border-line/60 flex items-start gap-2.5\">\n"
  "              <span class=\"px-1.5 py-0.5 rounded bg-signal/20 text-signal font-mono font-bold text-[10px]\">02</span>\n"
  "              <div><strong class=\"text-ink\">Сворачивание в спираль ($0.35 < t \le 1.00$):</strong> Дуга поджимается под таз и закручивается в плотное ядро A-01 ($+95&deg;$) со строгим сохранением монотонного сужения.</div>\n"
  "            </div>\n"
  "            <div class=\"p-2.5 rounded-xl bg-surface/40 border border-line/60 flex items-start gap-2.5\">\n"
  "              <span class=\"px-1.5 py-0.5 rounded bg-emerald-500/20 text-emerald-400 font-mono font-bold text-[10px]\">03</span>\n"
  "              <div><strong class=\"text-ink\">Нулевой оверхед ($O(1)$ память):</strong> Прямой расчет сплайна на лету занимает менее 0.05 мс на кадр, гарантируя стабильные 120 FPS.</div>\n"
  "            </div>\n"
  "          </div>\n"
  "        </div>\n"
  "      </div>\n"
  "    </div>\n"
  "\n"
  "  </div>\n"
  "</div>\n"
  "<script>\n"
  "  if (typeof window.scrubMascotLab === 'undefined') {\n"
  "    window.scrubMascotLab = function(val) {\n"
  "      var p = parseFloat(val);\n"
  "      var label = document.getElementById('mascot-lab-progress-val');\n"
  "      if (label) {\n"
  "        var pct = Math.round(p * 100);\n"
  "        label.innerText = pct + '% ' + (p === 0 ? '(U-03 Vine)' : (p === 1 ? '(A-01 Folded)' : '(Morphing)'));\n"
  "      }\n"
  "      var spEl = document.getElementById('mascot-lab-spine');\n"
  "      var blEl = document.getElementById('mascot-lab-belly');\n"
  "      if (spEl && blEl && typeof getMorphedTailPaths === 'function') {\n"
  "        var morphed = getMorphedTailPaths(p);\n"
  "        spEl.setAttribute('d', morphed.spine);\n"
  "        blEl.setAttribute('d', morphed.belly);\n"
  "      }\n"
  "      var vineEl = document.getElementById('hero-cyber-liana');\n"
  "      if (vineEl) {\n"
  "        vineEl.style.opacity = Math.max(0, 1 - p * 1.8).toFixed(2);\n"
  "      }\n"
  "    };\n"
  "    setTimeout(function() { window.scrubMascotLab(0); }, 50);\n"
  "  }\n"
  "</script>")

(df renderMascotLabView [] -> Str
  :d "Renders MascotLabView for router"
  (viewMascotLab))
