(module asl-web/in-browser-addie
  :d "In-Browser Autonomous Agent (Addie): WebGPU micro-model orchestrator, positional 1-2 token grammar & anti-hallucination firewall."
  :x [BrowserAgentModel PositionalToolkind AgentExecutionReport
      supported-browser-models default-browser-model
      detect-positional-tool extract-tool-payload
      validate-action-firewall balance-delimiters-fast]
  :i [(core/strings :a s)])

(dfe BrowserAgentModel
  (:c qwen-3b-q4 [] "Qwen 2.5 Coder 3B Instruct (Quantized Q4_K_M, ~2.0GB download / 2.8GB VRAM, 25 tok/s)")
  (:c qwen-15b-q4 [] "Qwen 2.5 Coder 1.5B Instruct (Quantized Q4_K_M, ~850MB download / 1.6GB VRAM, 38 tok/s)")
  (:c qwen-05b-q4 [] "Qwen 2.5 Coder 0.5B (Quantized Q4_K_M, ~240MB download / 945MB VRAM, 55 tok/s)")
  (:c qwen-05b-fp16 [] "Qwen 2.5 Coder 0.5B (Unquantized q0f16, ~980MB download / 1.6GB VRAM, 45 tok/s)")
  (:c large-host-boost [] "Frontier Large Model via Host Daemon or Cloud Endpoint (Button-Activatable Boost Mode)"))

(dfe PositionalToolkind
  (:c tool-html [] "Positional HTML execution: (:c :html ...)")
  (:c tool-svg [] "Positional SVG rendering: (:c :svg ...)")
  (:c tool-direct [] "Direct raw output payload"))

(dfs AgentExecutionReport
  (:f model-id Str "Selected model identifier")
  (:f toolkind PositionalToolkind "Detected toolkind from stream")
  (:f raw-tokens I64 "Token count generated by WebGPU")
  (:f syntax-repaired Bool "True if FSM normalizer repaired unclosed delimiters")
  (:f sanitized Bool "True if action firewall sanitized unsafe scripts")
  (:f payload Str "Clean verified code ready for sandbox execution"))

(df supported-browser-models [] -> (List Str)
  :d "Returns canonical list of in-browser WebGPU model identifiers."
  (list "qwen-coder-3b-q4" "qwen-coder-1.5b-q4" "qwen-coder-0.5b-q4" "qwen-coder-0.5b-fp16" "large-host-boost"))

(df default-browser-model [] -> Str
  :d "Returns recommended default model for client-side execution."
  "qwen-coder-1.5b-q4")

(df detect-positional-tool [(raw Str)] -> PositionalToolkind
  :d "Detects 1-2 token positional ASN tool calling from raw stream."
  (let [(clean (s/trim raw))]
    (cond
      ((or (s/starts-with? clean "(:c :html") (s/starts-with? clean "(:call :html")) (tool-html))
      ((or (s/starts-with? clean "(:c :svg") (s/starts-with? clean "(:call :svg")) (tool-svg))
      (true (tool-direct)))))

(df extract-tool-payload [(raw Str) (toolkind PositionalToolkind)] -> Str
  :d "Extracts inner code payload from positional ASN call."
  (let [(clean (s/trim raw))]
    (mt toolkind
      ((tool-html)
       (let [(after-prefix (s/slice clean 9 (s/len clean)))]
         (if (s/ends-with? after-prefix ")")
             (s/trim (s/slice after-prefix 0 (- (s/len after-prefix) 1)))
             (s/trim after-prefix))))
      ((tool-svg)
       (let [(after-prefix (s/slice clean 8 (s/len clean)))]
         (if (s/ends-with? after-prefix ")")
             (s/trim (s/slice after-prefix 0 (- (s/len after-prefix) 1)))
             (s/trim after-prefix))))
      ((tool-direct) clean))))

(df validate-action-firewall [(code Str)] -> Str
  :d "Sanitizes dangerous execution patterns before browser sandbox dispatch."
  (if (or (s/contains? code "document.cookie") (s/contains? code "localStorage"))
      "/* [FIREWALL BLOCKED] */"
      code))

(df balance-delimiters-fast [(code Str)] -> Str
  :d "Ensures balanced closing tags for HTML/SVG containers."
  (let [(c (s/trim code))]
    (if (and (s/contains? c "<div") (not (s/contains? c "</div>")))
        (s/concat c "</div>")
        (if (and (s/contains? c "<svg") (not (s/contains? c "</svg>")))
            (s/concat c "</svg>")
            c))))
