(module aslWeb/inBrowserEddie
  :d "In-Browser Autonomous Agent (Addie): WebGPU micro-model orchestrator, positional 1-2 token grammar & anti-hallucination firewall."
  :x [BrowserAgentModel PositionalToolkind AgentExecutionReport
      supportedBrowserModels defaultBrowserModel
      detectPositionalTool extractToolPayload
      validateActionFirewall balanceDelimitersFast]
  :i [(asl-text/string :a s)])

(dfe BrowserAgentModel
  (:c qwen3bQ4 [] "Qwen 2.5 Coder 3B Instruct (Quantized Q4_K_M, ~2.0GB download / 2.8GB VRAM, 25 tok/s)")
  (:c qwen15bQ4 [] "Qwen 2.5 Coder 1.5B Instruct (Quantized Q4_K_M, ~850MB download / 1.6GB VRAM, 38 tok/s)")
  (:c qwen05bQ4 [] "Qwen 2.5 Coder 0.5B (Quantized Q4_K_M, ~240MB download / 945MB VRAM, 55 tok/s)")
  (:c qwen05bFp16 [] "Qwen 2.5 Coder 0.5B (Unquantized q0f16, ~980MB download / 1.6GB VRAM, 45 tok/s)")
  (:c largeHostBoost [] "Frontier Large Model via Host Daemon or Cloud Endpoint (Button-Activatable Boost Mode)"))

(dfe PositionalToolkind
  (:c toolHtml [] "Positional HTML execution: (:c :html ...)")
  (:c toolSvg [] "Positional SVG rendering: (:c :svg ...)")
  (:c toolDirect [] "Direct raw output payload"))

(dfs AgentExecutionReport
  (:f modelId Str "Selected model identifier")
  (:f toolkind PositionalToolkind "Detected toolkind from stream")
  (:f rawTokens I64 "Token count generated by WebGPU")
  (:f syntaxRepaired Bool "True if FSM normalizer repaired unclosed delimiters")
  (:f sanitized Bool "True if action firewall sanitized unsafe scripts")
  (:f payload Str "Clean verified code ready for sandbox execution"))

(df supportedBrowserModels [] -> (List Str)
  :d "Returns canonical list of in-browser WebGPU model identifiers."
  (list "qwen-coder-3b-q4" "qwen-coder-1.5b-q4" "qwen-coder-0.5b-q4" "qwen-coder-0.5b-fp16" "large-host-boost"))

(df defaultBrowserModel [] -> Str
  :d "Returns recommended default model for client-side execution."
  "qwen-coder-1.5b-q4")

(df detectPositionalTool [(raw Str)] -> PositionalToolkind
  :d "Detects 1-2 token positional ASN tool calling from raw stream."
  (let [(clean (s/trim raw))]
    (cond
      ((or (s/startsWith? clean "(:c :html") (s/startsWith? clean "(:call :html")) (toolHtml))
      ((or (s/startsWith? clean "(:c :svg") (s/startsWith? clean "(:call :svg")) (toolSvg))
      (true (toolDirect)))))

(df extractToolPayload [(raw Str) (toolkind PositionalToolkind)] -> Str
  :d "Extracts inner code payload from positional ASN call."
  (let [(clean (s/trim raw))]
    (mt toolkind
      ((toolHtml)
       (let [(afterPrefix (s/slice clean 9 (s/len clean)))]
         (if (s/endsWith? afterPrefix ")")
             (s/trim (s/slice afterPrefix 0 (- (s/len afterPrefix) 1)))
             (s/trim afterPrefix))))
      ((toolSvg)
       (let [(afterPrefix (s/slice clean 8 (s/len clean)))]
         (if (s/endsWith? afterPrefix ")")
             (s/trim (s/slice afterPrefix 0 (- (s/len afterPrefix) 1)))
             (s/trim afterPrefix))))
      ((toolDirect) clean))))

(df validateActionFirewall [(code Str)] -> Str
  :d "Sanitizes dangerous execution patterns before browser sandbox dispatch."
  (if (or (s/contains? code "document.cookie") (s/contains? code "localStorage"))
      "/* [FIREWALL BLOCKED] */"
      code))

(df balanceDelimitersFast [(code Str)] -> Str
  :d "Ensures balanced closing tags for HTML/SVG containers."
  (let [(c (s/trim code))]
    (if (and (s/contains? c "<div") (not (s/contains? c "</div>")))
        (s/concat c "</div>")
        (if (and (s/contains? c "<svg") (not (s/contains? c "</svg>")))
            (s/concat c "</svg>")
            c))))
