#!/usr/bin/env python3
"""Tier A: every admissible instantiation of every builtin must compile.

"Exercised" never meant "the lowering works" — it meant "the lowering works at
the one type someone happened to use". `/` and `mod` sat inside the exercised set
while being declared `N N -> N` and lowered to `i64`-only runtime helpers, so
every gate was green and two thirds of their declared domain did not compile.

An *instantiation* is a builtin paired with one concrete assignment to every type
variable in its declared signature. The set is generated from prelude.json via
`parse_signature`, never hand-listed, so a builtin cannot be quietly left out.
Effectful, variadic and higher-order builtins are excluded — each is recorded
with its reason here and in `prelude/coverage.lock`, because an exclusion nothing
writes down is a skip list under another name.

Admissible means the checker accepts it: a probe the checker rejects is not a
lowering bug but a signature the language has narrowed (`map-key-order`), and the
count of those is pinned too, so narrowing cannot be used to hide a failure.

Exit code is the number of failing probes plus the number of lock disagreements.
"""
import argparse
import itertools
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "prelude"))
sys.path.insert(0, str(ROOT / "checker"))
sys.path.insert(0, str(Path(__file__).parent))

from vocab import parse_signature  # noqa: E402
from resolve import check_file  # noqa: E402
from to_python import Transpiler  # noqa: E402
from to_rust import ToRust  # noqa: E402

PRELUDE = json.loads((ROOT / "prelude" / "prelude.json").read_text())
LOCK = ROOT / "prelude" / "coverage.lock"

# `N` is the numeric variable of the vocabulary; every other variable ranges over
# the primitives a probe can write a literal-free signature for.
DOMAINS = {"N": ["Int32", "Int64", "Float64"],
           "*": ["Int64", "Float64", "String", "Bool"]}

HEADER = "; Generated by backend/monomorphism.py. Not a corpus fixture.\n"
PROBE_LINE = re.compile(r"^\(defun probe-(\d+) ")


class ProbeMismatch(RuntimeError):
    """A diagnostic that names no probe. Admissibility is then undetermined for
    every probe, so the sweep must stop rather than report a set it did not
    narrow: `check_file` answers a parse error or a checker crash with line 0,
    which arithmetic once turned into a real index and blamed the wrong probe
    while keeping all of them."""


def _vars(spec: dict, out: set[str]) -> None:
    if "var" in spec:
        out.add(spec["var"])
    elif "fn" in spec:
        for p in spec["fn"]:
            _vars(p, out)
        _vars(spec["ret"], out)
    else:
        for a in spec["args"]:
            _vars(a, out)


def _has_fn(spec: dict) -> bool:
    if "fn" in spec:
        return True
    return "con" in spec and any(_has_fn(a) for a in spec["args"])


def _render(spec: dict, subst: dict[str, str]) -> str:
    if "var" in spec:
        return subst[spec["var"]]
    if "fn" in spec:
        params = " ".join(_render(p, subst) for p in spec["fn"])
        return f"(fn [{params}] -> {_render(spec['ret'], subst)})"
    if not spec["args"]:
        return spec["con"]
    return "(" + spec["con"] + " " + " ".join(_render(a, subst) for a in spec["args"]) + ")"


def classify() -> tuple[dict[str, list[str]], list[dict]]:
    """(exclusions by reason, the builtins that get probed)."""
    excluded: dict[str, list[str]] = {"effect": [], "variadic": [],
                                      "higher-order": [], "monomorphic": []}
    probed = []
    for b in PRELUDE["builtins"]:
        args, variadic, ret = parse_signature(b["type"])
        seen: set[str] = set()
        for a in args:
            _vars(a, seen)
        _vars(ret, seen)
        if b.get("effect"):
            excluded["effect"].append(b["name"])
        elif variadic:
            excluded["variadic"].append(b["name"])
        elif any(_has_fn(a) for a in args) or _has_fn(ret):
            excluded["higher-order"].append(b["name"])
        elif not seen:
            excluded["monomorphic"].append(b["name"])
        else:
            probed.append({"name": b["name"], "args": args, "ret": ret,
                           "vars": sorted(seen)})
    return excluded, probed


def candidates() -> list[dict]:
    """Every (builtin x concrete assignment), before the checker narrows them."""
    out = []
    for entry in classify()[1]:
        domains = [DOMAINS.get(v, DOMAINS["*"]) for v in entry["vars"]]
        for combo in itertools.product(*domains):
            subst = dict(zip(entry["vars"], combo, strict=True))
            params = [_render(a, subst) for a in entry["args"]]
            out.append({
                "builtin": entry["name"],
                "subst": subst,
                "params": params,
                "ret": _render(entry["ret"], subst),
            })
    return out


def probe_source(probes: list[dict]) -> str:
    """One line per probe, so a diagnostic's line number names its probe."""
    lines = [HEADER.rstrip("\n")]
    for i, p in enumerate(probes):
        binders = " ".join(f"(a{j} {t})" for j, t in enumerate(p["params"]))
        call = " ".join([p["builtin"]] + [f"a{j}" for j in range(len(p["params"]))])
        lines.append(f"(defun probe-{i} [{binders}] -> {p['ret']} ({call}))")
    return "\n".join(lines) + "\n"


def probe_index_by_line(src: str) -> dict[int, int]:
    """Line number -> probe index, read off the emitted text. Derived rather than
    computed from an offset, because an offset that drifts from the source still
    produces a plausible index."""
    return {n: int(m.group(1))
            for n, line in enumerate(src.splitlines(), 1)
            if (m := PROBE_LINE.match(line))}


def label(p: dict) -> str:
    subst = ",".join(f"{k}={v}" for k, v in sorted(p["subst"].items()))
    return f"{p['builtin']} [{subst}]"


def runtime_source() -> str:
    return (ROOT / "backend" / "rust" / "rt.rs").read_text()


def _rustc(rs_src: str, workdir: Path) -> subprocess.CompletedProcess:
    (workdir / "rt.rs").write_text(runtime_source())
    (workdir / "lib.rs").write_text(rs_src)
    return subprocess.run(["rustup", "run", "stable", "rustc", "--edition", "2021",
                           "--crate-type=lib", "lib.rs"],
                          cwd=workdir, capture_output=True, text=True)


def _py_compile(py_src: str, workdir: Path) -> subprocess.CompletedProcess:
    (workdir / "cand.py").write_text(py_src)
    return subprocess.run([sys.executable, "-m", "py_compile", "cand.py"],
                          cwd=workdir, capture_output=True, text=True)


def compile_batch(probes: list[dict]) -> tuple[bool, bool]:
    """(rust accepted, python accepted) for one batch of probes."""
    src = probe_source(probes)
    with tempfile.TemporaryDirectory(dir="/tmp") as d:
        work = Path(d)
        rs = _rustc(ToRust().transpile(src), work).returncode == 0
        py = _py_compile(Transpiler().transpile(src), work).returncode == 0
    return rs, py


def guilty(probes: list[dict]) -> list[str]:
    """Which probes a failing batch is failing on, narrowed builtin-first so the
    per-probe pass runs over tens of probes rather than hundreds."""
    by_builtin: dict[str, list[dict]] = {}
    for p in probes:
        by_builtin.setdefault(p["builtin"], []).append(p)
    bad = []
    for name, group in sorted(by_builtin.items()):
        if all(compile_batch(group)):
            continue
        for p in group:
            rs, py = compile_batch([p])
            if not (rs and py):
                bad.append(f"{label(p)}: " + ", ".join(
                    t for t, ok in (("rustc", rs), ("py_compile", py)) if not ok)
                    + " rejected the lowering")
    return bad


def tier_a_summary() -> dict:
    """The shape `prelude/coverage.lock` records, so a shrunk sweep is visible."""
    excluded, _ = classify()
    admissible, narrowed = admissible_set()
    return {"probes": len(admissible),
            "narrowed": sorted(label(p) for p in narrowed),
            "domains": DOMAINS, "excluded": excluded}


def admissible_set() -> tuple[list[dict], list[dict]]:
    """(probes the checker accepts, probes it narrows away).

    Admissibility is asked of the checker rather than restated here: duplicating
    `map-key-order` in the sweep would let the two drift, and the sweep is what
    would then report success.
    """
    probes = candidates()
    src = probe_source(probes)
    with tempfile.TemporaryDirectory(dir="/tmp") as d:
        path = Path(d) / "probes.agentscript"
        path.write_text(src)
        diags = check_file(path, [])
    by_line = probe_index_by_line(src)
    if sorted(by_line.values()) != list(range(len(probes))):
        raise ProbeMismatch(
            f"probe source carries {len(by_line)} probe lines for {len(probes)} probes")
    rejected: dict[int, list[str]] = {}
    unmapped = [d for d in diags if d.line not in by_line]
    if unmapped:
        raise ProbeMismatch(
            f"{len(unmapped)} diagnostic(s) name no probe line, so no probe is known "
            "to be admissible: " + "; ".join(str(d) for d in unmapped[:3]))
    for diag in diags:
        rejected.setdefault(by_line[diag.line], []).append(diag.code)
    ok = [p for i, p in enumerate(probes) if i not in rejected]
    narrowed = [dict(probes[i], codes=sorted(set(rejected[i]))) for i in sorted(rejected)]
    return ok, narrowed


def check_lock(summary: dict) -> list[str]:
    """Fewer probes than the lock is a regression, more is a stale lock, and a
    changed domain or exclusion set is the sweep being shrunk instead of fixed."""
    if not LOCK.exists():
        return [f"{LOCK} does not exist"]
    want = json.loads(LOCK.read_text()).get("tier_a")
    if want is None:
        return [f"{LOCK} has no tier_a block"]
    out = []
    if summary["probes"] < want["probes"]:
        out.append(f"tier_a.probes: {summary['probes']} < lock {want['probes']} — "
                   "the sweep shrank; fix the builtin, do not narrow the sweep")
    if summary["probes"] > want["probes"]:
        out.append(f"tier_a.probes: {summary['probes']} > lock {want['probes']} — "
                   "stale lock; record the new count deliberately")
    for field in ("narrowed", "domains", "excluded"):
        if summary[field] != want.get(field):
            out.append(f"tier_a.{field} disagrees with {LOCK.name}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    excluded, probed = classify()
    try:
        admissible, narrowed = admissible_set()
    except ProbeMismatch as exc:
        print(f"  {exc}")
        print("\n1 failure(s)")
        return 1

    unexpected = [f"{label(p)}: checker reported {','.join(p['codes'])}"
                  for p in narrowed if p["codes"] != ["map-key-order"]]

    rs_ok, py_ok = compile_batch(admissible)
    failures = [] if (rs_ok and py_ok) else guilty(admissible)
    if not failures and not (rs_ok and py_ok):
        failures = ["the batch was rejected but no single probe reproduces it"]

    if not args.quiet:
        print(f"probed builtins : {len(probed)}")
        for reason, names in excluded.items():
            print(f"  excluded [{reason:<13}] {len(names):>3}: {' '.join(names)}")
        print(f"candidates      : {len(admissible) + len(narrowed)}")
        print(f"narrowed        : {len(narrowed)} (map-key-order)")
        print(f"probes          : {len(admissible)}")
        print(f"checker diags   : {len(unexpected)}")
        print(f"rustc           : {'ok' if rs_ok else 'FAIL'}")
        print(f"py_compile      : {'ok' if py_ok else 'FAIL'}")

    lock = check_lock(tier_a_summary())
    for line in unexpected + failures + lock:
        print("  " + line)
    total = len(unexpected) + len(failures) + len(lock)
    print(f"\n{total} failure(s)")
    return total


if __name__ == "__main__":
    sys.exit(main())
