(module asl-plugin/dynamicToolTest
  :d "Strict falsifiable test suite for dynamic tool plane on demand."
  :x [runTests]
  :i [(dynamic_tool :a dt)
      (asl-text/text :a txt)])

(df testEmptyPlaneAndBaseTools [] -> Bool
  :d "Verifies initial empty plane contains strictly 4 base meta-tools and satisfies base landscape."
  (let [(plane (dt/emptyPlane))
        (tools (dt/baseTools))]
    (assert (= (list-length tools) 4) "Base tools must contain exactly 4 meta-tools")
    (assert (list-contains? tools "eval") "Base tools must contain eval")
    (assert (list-contains? tools "batch") "Base tools must contain batch")
    (assert (list-contains? tools "tool-load") "Base tools must contain tool-load")
    (assert (list-contains? tools "tool-unload") "Base tools must contain tool-unload")
    (assert (dt/baseLandscape? plane) "Empty plane must satisfy base-landscape predicate")
    (assert (= (dt/toolCount plane) 4) "Initial tool count must be exactly 4")
    true))

(df testDomainLoadingAndLookup [] -> Bool
  :d "Verifies dynamic loading of domain tool definitions and in-plane lookups."
  (let [(p1 (dt/createParam "sym" ":str" false "Target symbol name"))
        (p2 (dt/createParam "format" ":str" true "Output format option"))
        (t1 (dt/createTool "callers" "intel" (list p1 p2) "(:graph :callers)" "Find callers" "(:graph (Caller > Target:call Line:int))"))
        (dIntel (dt/createDomain "intel" "Code intelligence" (list t1) "(:graph (Node > Target:edge))"))
        (plane (dt/emptyPlane))
        (pMounted (dt/loadDomain plane dIntel))]
    (assert (= (.-name p1) "sym") "Param name must match")
    (assert (= (.-paramType p1) ":str") "Param type must match")
    (assert (= (.-name t1) "callers") "Tool name must match")
    (assert (= (.-domain t1) "intel") "Tool domain must match")
    (assert (= (.-name dIntel) "intel") "Domain name must match")
    (assert (= (list-length (.-tools dIntel)) 1) "Domain must contain 1 tool")
    (assert (dt/domainLoaded? pMounted "intel") "Intel domain must be marked loaded")
    (refute (dt/baseLandscape? pMounted) "Mounted plane must not be base landscape")
    (assert (= (dt/toolCount pMounted) 5) "Tool count must increase to 5")
    (assert (dt/hasTool? pMounted "callers") "Mounted tool callers must be accessible")
    (assert (dt/hasTool? pMounted "eval") "Base meta-tool eval must remain accessible")
    (assert (is-some? (dt/lookupTool pMounted "callers")) "Lookup for callers must return some")
    (assert (is-none? (dt/lookupTool pMounted "nonexistent")) "Lookup for unknown tool must return none")
    true))

(df testDomainUnloadingAndReceipts [] -> Bool
  :d "Verifies unloading mounted domains and generation of structured step receipts."
  (let [(p1 (dt/createParam "sym" ":str" false "Target symbol"))
        (t1 (dt/createTool "callers" "intel" (list p1) ":graph" "Find callers" ""))
        (dIntel (dt/createDomain "intel" "Code intelligence" (list t1) ""))
        (plane (dt/emptyPlane))
        (pMounted (dt/loadDomain plane dIntel))
        (rcpt (dt/mountReceipt dIntel))
        (pUnmounted (dt/unloadDomain pMounted "intel"))
        (uRcpt (dt/unmountReceipt "intel" 1))]
    (assert (= (.-status rcpt) "ok") "Mount receipt status must be ok")
    (assert (= (.-mountedCount rcpt) 1) "Mount receipt count must be 1")
    (assert (= (.-domain rcpt) "intel") "Mount receipt domain must be intel")
    (refute (dt/domainLoaded? pUnmounted "intel") "Intel domain must not be loaded after unload")
    (refute (dt/hasTool? pUnmounted "callers") "Callers tool must not be present after unload")
    (assert (dt/baseLandscape? pUnmounted) "Tool plane must revert to base landscape after unload")
    (assert (= (dt/toolCount pUnmounted) 4) "Tool count must revert to 4")
    (assert (= (.-status uRcpt) "ok") "Unmount receipt status must be ok")
    (assert (= (.-unmountedCount uRcpt) 1) "Unmount receipt count must be 1")
    true))

(df testTurnResetAndTokenLandscape [] -> Bool
  :d "Verifies turn boundary reset discarding mounts and token footprint <= 200."
  (let [(p1 (dt/createParam "path" ":str" false "File path"))
        (t1 (dt/createTool "read" "fs" (list p1) ":str" "Read file" ""))
        (dFs (dt/createDomain "fs" "Filesystem operations" (list t1) ""))
        (plane (dt/emptyPlane))
        (pMounted (dt/loadDomain plane dFs))
        (pReset (dt/resetTurn pMounted))
        (lsEmpty (dt/activeLandscape (dt/emptyPlane)))
        (lsMounted (dt/activeLandscape pMounted))]
    (assert (dt/baseLandscape? pReset) "Plane after turn reset must be base landscape")
    (assert (= (dt/toolCount pReset) 4) "Reset plane must have exactly 4 tools")
    (assert (.-baseOnly lsEmpty) "Empty landscape base-only flag must be true")
    (assert (= (.-totalCount lsEmpty) 4) "Empty landscape tool count must be 4")
    (assert (< (.-tokenFootprint lsEmpty) 200) "Base landscape token footprint must be <= 200")
    (refute (.-baseOnly lsMounted) "Mounted landscape base-only flag must be false")
    (assert (= (.-totalCount lsMounted) 5) "Mounted landscape tool count must be 5")
    true))

(df testAdjacencyGraphDsl [] -> Bool
  :d "Verifies Adjacency DSL formatting schema (:graph (Node > Target1:edge Target2:edge))."
  (let [(g1 (dt/formatGraph "CallerA" (list "TargetB:call" "TargetC:call")))
        (g2 (dt/formatGraph "Leaf" (list)))]
    (assert (= g1 "(:graph (CallerA > TargetB:call TargetC:call))") "Adjacency DSL must match expected format")
    (assert (string-contains? g1 ">") "Adjacency DSL must contain transition symbol >")
    (assert (string-contains? g1 "CallerA") "Adjacency DSL must contain source node")
    (assert (= g2 "(:graph (Leaf))") "Empty edge graph must format without transition symbol")
    true))

(df testDenseToolRendering [] -> Bool
  :d "Verifies compact Dense Keyword Signature rendering."
  (let [(r1 (dt/renderDenseTool "mem.query" "query [scope] [limit]" "vector semantic search AST"))
        (r2 (dt/renderDenseTool "mem.flush" "" "persist staged edits disk"))]
    (assert (= r1 "(:tool :name \"mem.query\" :sig \"query [scope] [limit]\" :d \"vector semantic search AST\")") "Dense tool query matches format")
    (assert (= r2 "(:tool :name \"mem.flush\" :sig \"\" :d \"persist staged edits disk\")") "Dense tool flush matches format")
    (assert (string-contains? r1 ":name \"mem.query\"") "Query name present")
    (assert (string-contains? r1 ":sig \"query [scope] [limit]\"") "Query sig present")
    (assert (string-contains? r1 ":d \"vector semantic search AST\"") "Query doc present")
    (refute (string-contains? r1 ":schema") "Dense tool must not contain verbose schema")
    (refute (string-contains? r2 "old-schema") "Dense tool must not contain old schema")
    true))

(df testDenseKeywordDensityValidation [] -> Bool
  :d "Verifies lexical density invariant: docstrings strictly between 2 and 5 words."
  (let [(d1 "vector semantic search AST")
        (d2 "stage atomic string replacement")
        (d3 "inspect staged RAM diffs")
        (d4 "persist staged edits disk")
        (d5 "clear staged RAM buffers")
        (d6 "append durable memory ledger")
        (d7 "read section without disk")
        (d8 "render holistic hierarchy telemetry")
        (tooShort1 "search")
        (tooShort0 "")
        (tooLong1 "one two three four five six")
        (tooLong2 "this is a very long descriptive docstring exceeding maximum words")]
    (assert (= (dt/countWords d1) 4) "d1 word count is 4")
    (assert (= (dt/countWords d2) 4) "d2 word count is 4")
    (assert (= (dt/countWords d3) 4) "d3 word count is 4")
    (assert (= (dt/countWords d4) 4) "d4 word count is 4")
    (assert (= (dt/countWords d5) 4) "d5 word count is 4")
    (assert (= (dt/countWords d6) 4) "d6 word count is 4")
    (assert (= (dt/countWords d7) 4) "d7 word count is 4")
    (assert (= (dt/countWords d8) 4) "d8 word count is 4")
    (assert (dt/validDenseDoc? d1) "d1 is valid dense doc")
    (assert (dt/validDenseDoc? d2) "d2 is valid dense doc")
    (assert (dt/validDenseDoc? d3) "d3 is valid dense doc")
    (assert (dt/validDenseDoc? d4) "d4 is valid dense doc")
    (assert (dt/validDenseDoc? d5) "d5 is valid dense doc")
    (assert (dt/validDenseDoc? d6) "d6 is valid dense doc")
    (assert (dt/validDenseDoc? d7) "d7 is valid dense doc")
    (assert (dt/validDenseDoc? d8) "d8 is valid dense doc")
    (refute (dt/validDenseDoc? tooShort1) "Single word doc must be refuted")
    (refute (dt/validDenseDoc? tooShort0) "Empty doc must be refuted")
    (refute (dt/validDenseDoc? tooLong1) "6-word doc must be refuted")
    (refute (dt/validDenseDoc? tooLong2) "Long doc must be refuted")
    true))

(df testDenseLandscapeCompilation [] -> Bool
  :d "Verifies compilation of compact Turn 0 prompt block with token footprint <= 250."
  (let [(t1 (dt/renderDenseTool "mem.query" "query [scope] [limit]" "vector semantic search AST"))
        (t2 (dt/renderDenseTool "mem.edit" "file old new" "stage atomic string replacement"))
        (t3 (dt/renderDenseTool "mem.diff" "[file]" "inspect staged RAM diffs"))
        (t4 (dt/renderDenseTool "mem.flush" "" "persist staged edits disk"))
        (t5 (dt/renderDenseTool "mem.discard" "" "clear staged RAM buffers"))
        (t6 (dt/renderDenseTool "mem.write" "kind payload" "append durable memory ledger"))
        (t7 (dt/renderDenseTool "mem.doc" "file section" "read section without disk"))
        (t8 (dt/renderDenseTool "mem.tree" "[path]" "render holistic hierarchy telemetry"))
        (allDense (list t1 t2 t3 t4 t5 t6 t7 t8))
        (plane (dt/emptyPlane))
        (rendered (dt/renderDenseLandscape plane allDense))
        (tokens (txt/estimateTokens rendered))
        (emptyPlaneNoMeta (dt/ToolPlane :baseMeta (list) :activeDomains (list) :mountedTools (map-empty) :turnCounter 0))
        (renderedOnlyDense (dt/renderDenseLandscape emptyPlaneNoMeta allDense))
        (tokensOnlyDense (txt/estimateTokens renderedOnlyDense))]
    (assert (string-starts-with? rendered "(:tools [") "Dense landscape starts with :tools [")
    (assert (string-ends-with? rendered "])") "Dense landscape ends with ])")
    (assert (string-contains? rendered ":meta-tool :name \"eval\"") "Base meta eval included")
    (assert (string-contains? rendered ":meta-tool :name \"batch\"") "Base meta batch included")
    (assert (string-contains? rendered ":name \"mem.query\"") "mem.query included")
    (assert (string-contains? rendered ":name \"mem.edit\"") "mem.edit included")
    (assert (string-contains? rendered ":name \"mem.diff\"") "mem.diff included")
    (assert (string-contains? rendered ":name \"mem.flush\"") "mem.flush included")
    (assert (string-contains? rendered ":name \"mem.discard\"") "mem.discard included")
    (assert (string-contains? rendered ":name \"mem.write\"") "mem.write included")
    (assert (string-contains? rendered ":name \"mem.doc\"") "mem.doc included")
    (assert (string-contains? rendered ":name \"mem.tree\"") "mem.tree included")
    (assert (< tokens 300) "Full dense landscape token estimate must be < 300")
    (assert (< tokensOnlyDense 200) "Pure dense tools token estimate must be < 200")
    (refute (string-contains? renderedOnlyDense ":meta-tool") "Pure dense tools must not have meta tools")
    (refute (string-contains? rendered "unknown-tool") "Rendered landscape must not have unknown tools")
    true))

(df testLookupToolHelp [] -> Bool
  :d "Verifies dynamic lazy loading lookup without full schema mounting."
  (let [(hQuery (dt/lookupToolHelp "mem.query"))
        (hQueryShort (dt/lookupToolHelp "query"))
        (hEdit (dt/lookupToolHelp "mem.edit"))
        (hReplace (dt/lookupToolHelp "replace"))
        (hDiff (dt/lookupToolHelp "mem.diff"))
        (hFlush (dt/lookupToolHelp "mem.flush"))
        (hDiscard (dt/lookupToolHelp "mem.discard"))
        (hWrite (dt/lookupToolHelp "mem.write"))
        (hDoc (dt/lookupToolHelp "mem.doc"))
        (hTree (dt/lookupToolHelp "mem.tree"))
        (hDomain (dt/lookupToolHelp "mem"))
        (hEval (dt/lookupToolHelp "eval"))
        (hUnknown (dt/lookupToolHelp "nonexistent"))]
    (assert (is-some? hQuery) "mem.query help found")
    (assert (is-some? hQueryShort) "query alias help found")
    (assert (string-contains? (option-or hQuery "") ":tool \"mem.query\"") "Query help contains tool name")
    (assert (string-contains? (option-or hQuery "") ":status :help") "Query help contains status help")
    (assert (is-some? hEdit) "mem.edit help found")
    (assert (is-some? hReplace) "replace alias help found")
    (assert (string-contains? (option-or hEdit "") ":alias [\"replace\"]") "Edit help contains alias")
    (assert (is-some? hDiff) "mem.diff help found")
    (assert (is-some? hFlush) "mem.flush help found")
    (assert (is-some? hDiscard) "mem.discard help found")
    (assert (string-contains? (option-or hDiscard "") "Non-destructive on help") "Discard contains non-destructive guard")
    (assert (is-some? hWrite) "mem.write help found")
    (assert (is-some? hDoc) "mem.doc help found")
    (assert (is-some? hTree) "mem.tree help found")
    (assert (is-some? hDomain) "mem domain help found")
    (assert (string-contains? (option-or hDomain "") ":domain \"mem\"") "Domain help contains domain mem")
    (assert (is-some? hEval) "eval help found")
    (assert (is-none? hUnknown) "Unknown tool returns none")
    (refute (is-some? hUnknown) "Unknown tool must refute is-some")
    true))

(df runTests [] -> Bool
  :d "Runs all dynamic tool plane test suites."
  (and (testEmptyPlaneAndBaseTools)
       (and (testDomainLoadingAndLookup)
            (and (testDomainUnloadingAndReceipts)
                 (and (testTurnResetAndTokenLandscape)
                      (and (testAdjacencyGraphDsl)
                           (and (testDenseToolRendering)
                                (and (testDenseKeywordDensityValidation)
                                     (and (testDenseLandscapeCompilation)
                                          (testLookupToolHelp))))))))))
