(module asl-codegen/builtins
  :d "Builtin lowering templates and rendering for the 107 Core ASL builtins."
  :x [builtin-template
      render-template
      render-builtin]
  :i [])

(df builtin-template [(name String)] -> (Option String)
  :d "Returns the Rust lowering template for a Core builtin."
  (cond
    ((= name "!=") (some "({0} != {1})"))
    ((= name "*") (some "rt::mul({0}, {1})"))
    ((= name "+") (some "rt::add({0}, {1})"))
    ((= name "-") (some "rt::sub({0}, {1})"))
    ((= name "/") (some "rt::div({0}, {1})"))
    ((= name "<") (some "({0} < {1})"))
    ((= name "<=") (some "({0} <= {1})"))
    ((= name "=") (some "({0} == {1})"))
    ((= name ">") (some "({0} > {1})"))
    ((= name ">=") (some "({0} >= {1})"))
    ((= name "abs") (some "rt::abs({0})"))
    ((= name "already-exists") (some "rt::IoError::AlreadyExists"))
    ((= name "and") (some "({0} && {1})"))
    ((= name "checked-div") (some "rt::checked_div({0}, {1})"))
    ((= name "checked-mod") (some "rt::checked_rem({0}, {1})"))
    ((= name "eprintln") (some "rt::eprintln(&{0})"))
    ((= name "err") (some "Err({0})"))
    ((= name "file-append") (some "rt::file_append(&{0}, &{1})"))
    ((= name "file-exists?") (some "rt::file_exists(&{0})"))
    ((= name "file-read") (some "rt::file_read(&{0})"))
    ((= name "file-write") (some "rt::file_write(&{0}, &{1})"))
    ((= name "filter") (some "rt::filter({1}, {0})"))
    ((= name "float64-to-int64") (some "rt::f_to_i({0})"))
    ((= name "fold") (some "{2}.into_iter().fold({1}, {0})"))
    ((= name "int32-to-int64") (some "({0} as i64)"))
    ((= name "int64-to-float64") (some "rt::i_to_f({0})"))
    ((= name "int64-to-int32") (some "rt::to_i32({0})"))
    ((= name "interrupted") (some "rt::IoError::Interrupted"))
    ((= name "invalid-path") (some "rt::IoError::InvalidPath"))
    ((= name "is-err?") (some "{0}.is_err()"))
    ((= name "is-none?") (some "{0}.is_none()"))
    ((= name "is-ok?") (some "{0}.is_ok()"))
    ((= name "is-some?") (some "{0}.is_some()"))
    ((= name "list") (some "vec![{*}]"))
    ((= name "list-append") (some "rt::append({0}, {1})"))
    ((= name "list-cons") (some "rt::cons({0}, {1})"))
    ((= name "list-contains?") (some "{0}.contains(&{1})"))
    ((= name "list-empty?") (some "{0}.is_empty()"))
    ((= name "list-get") (some "rt::at(&{0}, {1})"))
    ((= name "list-head") (some "rt::at(&{0}, 0)"))
    ((= name "list-index-of") (some "rt::index_of(&{0}, &{1})"))
    ((= name "list-length") (some "({0}.len() as i64)"))
    ((= name "list-max") (some "rt::greatest(&{0})"))
    ((= name "list-min") (some "rt::least(&{0})"))
    ((= name "list-reverse") (some "rt::rev({0})"))
    ((= name "list-slice") (some "rt::list_slice(&{0}, {1}, {2})"))
    ((= name "list-sort") (some "rt::sort({0})"))
    ((= name "list-sort-by") (some "rt::sort_by({1}, {0})"))
    ((= name "list-sum") (some "rt::sum({0})"))
    ((= name "list-tail") (some "rt::tail(&{0})"))
    ((= name "map") (some "{1}.into_iter().map({0}).collect::<Vec<_>>()"))
    ((= name "map-empty") (some "std::collections::BTreeMap::new()"))
    ((= name "map-from-pairs") (some "rt::m_from({0})"))
    ((= name "map-get") (some "rt::m_get(&{0}, &{1})"))
    ((= name "map-has?") (some "{0}.contains_key(&{1})"))
    ((= name "map-keys") (some "{0}.keys().cloned().collect::<Vec<_>>()"))
    ((= name "map-pairs") (some "rt::m_pairs(&{0})"))
    ((= name "map-remove") (some "rt::m_del({0}, &{1})"))
    ((= name "map-set") (some "rt::m_set({0}, {1}, {2})"))
    ((= name "map-size") (some "({0}.len() as i64)"))
    ((= name "map-values") (some "{0}.values().cloned().collect::<Vec<_>>()"))
    ((= name "max") (some "rt::max({0}, {1})"))
    ((= name "min") (some "rt::min({0}, {1})"))
    ((= name "mod") (some "rt::rem({0}, {1})"))
    ((= name "neg") (some "rt::neg({0})"))
    ((= name "none") (some "None"))
    ((= name "not") (some "(!{0})"))
    ((= name "not-found") (some "rt::IoError::NotFound"))
    ((= name "ok") (some "Ok({0})"))
    ((= name "option-map") (some "{1}.map({0})"))
    ((= name "option-or") (some "{0}.unwrap_or({1})"))
    ((= name "option-to-result") (some "{0}.ok_or({1})"))
    ((= name "or") (some "({0} || {1})"))
    ((= name "other") (some "rt::IoError::Other"))
    ((= name "pair") (some "({0}, {1})"))
    ((= name "permission-denied") (some "rt::IoError::PermissionDenied"))
    ((= name "print") (some "rt::print_out(&{0})"))
    ((= name "println") (some "rt::println(&{0})"))
    ((= name "range") (some "rt::range({0}, {1})"))
    ((= name "read-all") (some "rt::read_all()"))
    ((= name "read-line") (some "rt::read_line()"))
    ((= name "result-map") (some "{1}.map({0})"))
    ((= name "result-map-err") (some "{1}.map_err({0})"))
    ((= name "result-or") (some "{0}.unwrap_or({1})"))
    ((= name "result-to-option") (some "{0}.ok()"))
    ((= name "some") (some "Some({0})"))
    ((= name "str") (some "rt::concat(&[{*}])"))
    ((= name "string-chars") (some "rt::chars(&{0})"))
    ((= name "string-contains?") (some "{0}.contains(&{1})"))
    ((= name "string-empty?") (some "{0}.is_empty()"))
    ((= name "string-ends-with?") (some "{0}.ends_with(&{1})"))
    ((= name "string-from-float64") (some "rt::fmt_f64({0})"))
    ((= name "string-from-int64") (some "rt::fmt_i64({0})"))
    ((= name "string-index-of") (some "rt::str_index_of(&{0}, &{1})"))
    ((= name "string-join") (some "{0}.join(&{1})"))
    ((= name "string-length") (some "rt::str_len(&{0})"))
    ((= name "string-lower") (some "{0}.to_lowercase()"))
    ((= name "string-replace") (some "{0}.replace(&{1}, &{2})"))
    ((= name "string-reverse") (some "rt::str_rev(&{0})"))
    ((= name "string-slice") (some "rt::str_slice(&{0}, {1}, {2})"))
    ((= name "string-split") (some "rt::split(&{0}, &{1})"))
    ((= name "string-starts-with?") (some "{0}.starts_with(&{1})"))
    ((= name "string-to-float64") (some "rt::to_f64(&{0})"))
    ((= name "string-to-int64") (some "rt::to_i64(&{0})"))
    ((= name "string-trim") (some "{0}.trim().to_string()"))
    ((= name "string-upper") (some "{0}.to_uppercase()"))
    ((= name "zip") (some "rt::zip({0}, {1})"))
    (:else (none))))

(df render-template [(tmpl String) (args (List String))] -> String
  :d "Substitutes {*}, {0}, {1}, {2} placeholders in a lowering template."
  (let [(t-star (if (string-contains? tmpl "{*}")
                    (string-replace tmpl "{*}" (string-join args ", "))
                    tmpl))
        (a0 (option-or (list-get args 0) ""))
        (t0 (if (string-contains? t-star "{0}")
                (string-replace t-star "{0}" a0)
                t-star))
        (a1 (option-or (list-get args 1) ""))
        (t1 (if (string-contains? t0 "{1}")
                (string-replace t0 "{1}" a1)
                t0))
        (a2 (option-or (list-get args 2) ""))
        (t2 (if (string-contains? t1 "{2}")
                (string-replace t1 "{2}" a2)
                t1))]
    t2))

(df render-builtin [(bname String) (args (List String))] -> (Option String)
  :d "Renders a builtin call into Rust expression syntax."
  (mt (builtin-template bname)
    ((none) (none))
    ((some tmpl) (some (render-template tmpl args)))))
