(module aslPack/targets/previewServer
  :d "Pure AgentScript HTTP dev-server orchestrator for mobile preview."
  :x [PreviewServerSpec
      makePreviewServerSpec
      formatHotReloadPatchFrame
      generatePreviewServerScript]
  :i [(asl-codec/asn :a asn)])

(df int-to-string [(n Int64)] -> Str
  :d "Converts integer to string representation."
  (string-from-int64 n))

(dfs PreviewServerSpec
  (:f port Int64 "HTTP listening port e.g. 8080")
  (:f heartbeatMs Int64 "Keepalive ping interval in milliseconds")
  (:f watchDir Str "Directory path monitored for AST updates"))

(df makePreviewServerSpec [(port Int64) (watchDir Str)] -> PreviewServerSpec
  :d "Constructs standard mobile preview dev server specification."
  (PreviewServerSpec
    :port port
    :heartbeatMs 30000
    :watchDir watchDir))

(df formatHotReloadPatchFrame [(targetScreen Str) (htmlPayload Str)] -> Str
  :d "Formats an atomic differential patch frame into compact JSON for the browser simulator."
  (str "{\"type\":\"patch\",\"screen\":" (asn/asnWrite (asn/asnStr targetScreen)) ",\"html\":" (asn/asnWrite (asn/asnStr htmlPayload)) "}"))

(df generatePreviewServerScript [(spec PreviewServerSpec)] -> Str
  :d "Emits a lightweight standalone Node.js/Bun HTTP server script."
  (let [(pStr (int-to-string (.-port spec)))
        (wDir (.-watchDir spec))]
    (str "// Auto-generated by asl-pack mobile preview server\n"
         "const http = require('http');\n"
         "const fs = require('fs');\n"
         "const path = require('path');\n"
         "const PORT = " pStr ";\n"
         "const server = http.createServer((req, res) => {\n"
         "  const urlPath = req.url.split('?')[0].split('#')[0];\n"
         "  const file = urlPath === '/' ? 'mobile_preview.html' : urlPath.slice(1);\n"
         "  const scratchDir = path.resolve(process.cwd(), 'scratch');\n"
         "  const filePath = path.resolve(scratchDir, file);\n"
         "  if (!filePath.startsWith(scratchDir + path.sep) && filePath !== scratchDir) {\n"
         "    res.writeHead(403);\n"
         "    res.end('Forbidden');\n"
         "    return;\n"
         "  }\n"
         "  if (fs.existsSync(filePath)) {\n"
         "    res.writeHead(200, { 'Content-Type': file.endsWith('.html') ? 'text/html' : 'text/plain' });\n"
         "    fs.createReadStream(filePath).pipe(res);\n"
         "  } else {\n"
         "    res.writeHead(404);\n"
         "    res.end('Not Found');\n"
         "  }\n"
         "});\n"
         "server.listen(PORT, () => console.log(`ASL Mobile Preview Server active at http://localhost:${PORT}`));\n")))
