(module aslPack/targets/swift
  :d "Swift Package Manager and Apple iOS/macOS AOT native bridge generator."
  :x [SwiftPackageSpec
      SwiftAppSpec
      generatePackageSwift
      generateCBridgeHeader
      generateXcframeworkScript
      generateSwiftuiEntrypoint
      generateSwiftObservableStore]
  :i [])

(dfs SwiftPackageSpec
  (:f pkgName Str "Swift package target name e.g. ASLKit")
  (:f iosMinVersion Str "Minimum iOS platform version e.g. v15")
  (:f macosMinVersion Str "Minimum macOS platform version e.g. v12")
  (:f cBridgeHeader Str "Header filename e.g. ASLBridge.h"))

(dfs SwiftAppSpec
  (:f appName Str "Application binary and product name e.g. ASLMobileApp")
  (:f bundleId Str "Apple reverse-DNS bundle identifier e.g. io.genseam.aslmobile")
  (:f iosMinVersion Str "Minimum iOS platform version e.g. v16")
  (:f packageName Str "Swift package target name e.g. ASLKit"))

(df generateCBridgeHeader [(pkgName Str)] -> Str
  :d "Emits pure C header declarations for AOT compiled AgentScript modules."
  (str "// Auto-generated by asl-pack for " pkgName "\n"
       "#ifndef ASL_BRIDGE_H\n"
       "#define ASL_BRIDGE_H\n\n"
       "#include <stdint.h>\n"
       "#include <stddef.h>\n\n"
       "#ifdef __cplusplus\n"
       "extern \"C\" {\n"
       "#endif\n\n"
       "typedef struct {\n"
       "    const uint8_t *data;\n"
       "    size_t length;\n"
       "} ASLByteBuffer;\n\n"
       "int32_t asl_init(void);\n"
       "ASLByteBuffer asl_eval(const char *module_name, const uint8_t *input_asn, size_t input_len);\n"
       "void asl_free_buffer(ASLByteBuffer buf);\n\n"
       "#ifdef __cplusplus\n"
       "}\n"
       "#endif\n\n"
       "#endif // ASL_BRIDGE_H\n"))

(df generatePackageSwift [(spec SwiftPackageSpec)] -> Str
  :d "Generates standard Package.swift manifest linking AOT static library."
  (let [(name (.-pkgName spec))
        (hdr (.-cBridgeHeader spec))]
    (str "// swift-tools-version: 5.9\n"
         "import PackageDescription\n\n"
         "let package = Package(\n"
         "    name: \"" name "\",\n"
         "    platforms: [.iOS(." (.-iosMinVersion spec) "), .macOS(." (.-macosMinVersion spec) ")],\n"
         "    products: [\n"
         "        .library(name: \"" name "\", targets: [\"" name "\"])\n"
         "    ],\n"
         "    targets: [\n"
         "        .target(\n"
         "            name: \"" name "\",\n"
         "            publicHeadersPath: \"include\",\n"
         "            cSettings: [.headerSearchPath(\"include\")]\n"
         "        )\n"
         "    ]\n"
         ")\n")))

(df generateXcframeworkScript [(pkgName Str) (outDir Str)] -> Str
  :d "Emits a shell script to build and package a multi-architecture XCFramework for physical devices and simulators."
  (str "#!/usr/bin/env bash\n"
       "set -euo pipefail\n"
       "echo \"Building " pkgName " multi-arch XCFramework in " outDir "...\"\n"
       "xcodebuild archive -scheme " pkgName " -destination \"generic/platform=iOS\" -archivePath \"" outDir "/ios.xcarchive\" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES\n"
       "xcodebuild archive -scheme " pkgName " -destination \"generic/platform=iOS Simulator\" -archivePath \"" outDir "/ios-sim.xcarchive\" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES\n"
       "xcodebuild -create-xcframework \\\n"
       "    -framework \"" outDir "/ios.xcarchive/Products/Library/Frameworks/" pkgName ".framework\" \\\n"
       "    -framework \"" outDir "/ios-sim.xcarchive/Products/Library/Frameworks/" pkgName ".framework\" \\\n"
       "    -output \"" outDir "/" pkgName ".xcframework\"\n"
       "echo \"XCFramework created successfully at " outDir "/" pkgName ".xcframework\"\n"))

(df generateSwiftuiEntrypoint [(appName Str)] -> Str
  :d "Emits standard SwiftUI 6 @main application scene entrypoint."
  (str "// Auto-generated by asl-pack for " appName "\n"
       "import SwiftUI\n\n"
       "@main\n"
       "struct " appName "App: App {\n"
       "    @State private var store = ASLStateStore()\n\n"
       "    var body: some Scene {\n"
       "        WindowGroup {\n"
       "            ContentView()\n"
       "                .environment(store)\n"
       "        }\n"
       "    }\n"
       "}\n"))

(df generateSwiftObservableStore [(storeName Str)] -> Str
  :d "Emits Swift 6 observation framework reactive store binding ASL native memory."
  (str "// Auto-generated by asl-pack for " storeName "\n"
       "import SwiftUI\n"
       "import Observation\n\n"
       "@Observable\n"
       "public final class " storeName " {\n"
       "    public var statePayload: String = \"{}\"\n"
       "    public var isEvaluating: Bool = false\n\n"
       "    public init() {}\n\n"
       "    public func dispatchAction(moduleName: String, actionPayload: String) {\n"
       "        self.isEvaluating = true\n"
       "        let rawBytes = [UInt8](actionPayload.utf8)\n"
       "        let resultBuf = asl_eval(moduleName, rawBytes, rawBytes.count)\n"
       "        if let data = resultBuf.data {\n"
       "            self.statePayload = String(decoding: UnsafeBufferPointer(start: data, count: resultBuf.length), as: UTF8.self)\n"
       "            asl_free_buffer(resultBuf)\n"
       "        }\n"
       "        self.isEvaluating = false\n"
       "    }\n"
       "}\n"))
