import React from 'react';
import { Cpu, ShieldCheck, Zap, ArrowRight, Code2 } from 'lucide-react';

export const Hero: React.FC = () => {
  return (
    <section className="relative pt-12 pb-16 border-b border-craft-800 bg-craft-950 grid-pattern">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl">
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full border border-craft-700 bg-craft-900/90 text-xs font-mono text-craft-accent mb-6 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-craft-accent animate-pulse" />
            <span>Self-Hosting WebAssembly Toolchain & MCP Server</span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-craft-50 font-mono leading-tight">
            Code generated by Agents.<br />
            <span className="text-craft-accent">Executed at native speed.</span>
          </h1>

          <p className="mt-6 text-lg text-craft-300 font-sans leading-relaxed">
            AgentScript is an S-expression language built for autonomous AI generation and deterministic edge sandboxing. Zero-cost types, total pattern matching, 78% lower token overhead, and direct compilation to WebAssembly, TypeScript, Rust, and Go.
          </p>

          <div className="mt-8 flex flex-wrap gap-4 items-center font-mono">
            <a
              href="#playground"
              className="px-5 py-3 rounded bg-craft-accent text-craft-950 font-semibold text-sm hover:bg-craft-accent/90 transition-all flex items-center gap-2 shadow-lg shadow-craft-accent/10"
            >
              <span>Try Live in Browser</span>
              <ArrowRight className="w-4 h-4" />
            </a>
            <a
              href="#targets"
              className="px-5 py-3 rounded bg-craft-900 border border-craft-700 text-craft-100 text-sm hover:border-craft-500 transition-colors flex items-center gap-2"
            >
              <Code2 className="w-4 h-4 text-craft-accent" />
              <span>Multi-Target Matrix</span>
            </a>
          </div>

          {/* Feature Highlights Grid */}
          <div className="mt-12 grid grid-cols-1 sm:grid-cols-3 gap-4 border-t border-craft-800/80 pt-8">
            <div className="p-4 rounded border border-craft-800 bg-craft-900/50">
              <div className="flex items-center gap-2 text-craft-accent font-mono text-sm font-semibold mb-1">
                <Cpu className="w-4 h-4" />
                <span>Pure Wasm Edge</span>
              </div>
              <p className="text-xs text-craft-400 font-mono">Instant in-browser WASI execution with memory isolation.</p>
            </div>

            <div className="p-4 rounded border border-craft-800 bg-craft-900/50">
              <div className="flex items-center gap-2 text-craft-accent font-mono text-sm font-semibold mb-1">
                <ShieldCheck className="w-4 h-4" />
                <span>100% Deterministic</span>
              </div>
              <p className="text-xs text-craft-400 font-mono">Exhaustive matching, effect tracking, zero unhandled errors.</p>
            </div>

            <div className="p-4 rounded border border-craft-800 bg-craft-900/50">
              <div className="flex items-center gap-2 text-craft-accent font-mono text-sm font-semibold mb-1">
                <Zap className="w-4 h-4" />
                <span>-78% Token Context</span>
              </div>
              <p className="text-xs text-craft-400 font-mono">Structured interface compressor saving LLM prompt budgets.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
