import React from 'react';
import { Cpu, ShieldCheck, Zap, ArrowRight, Terminal } from 'lucide-react';

export const Hero: React.FC = () => {
  return (
    <section className="relative pt-12 pb-16 border-b border-craft-800 bg-craft-950 grid-pattern">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl">
          <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full border border-craft-700 bg-craft-900/90 text-xs font-mono text-craft-accent mb-6 shadow-sm">
            <span className="w-2 h-2 rounded-full bg-craft-accent animate-pulse" />
            <span>The #1 Language for AI Agents & Vibe-Coding</span>
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-craft-50 font-mono leading-tight">
            Code generated by Agents.<br />
            <span className="text-craft-accent">Executed at native speed.</span>
          </h1>

          <p className="mt-6 text-lg text-craft-300 font-sans leading-relaxed">
            <strong>ASL (AgentScript Language)</strong> is the first programming language built from the ground up for the Agentic Era. Single-pass S-expressions, 0 syntax repair loops, 78% lower prompt token overhead, and instant zero-cost WebAssembly sandboxing.
          </p>

          {/* Fast-Track 1-Line Installer */}
          <div className="mt-8 p-3.5 rounded-xl border border-craft-700 bg-craft-900/90 shadow-xl max-w-2xl font-mono text-xs">
            <div className="flex items-center justify-between text-[11px] text-craft-400 mb-2 border-b border-craft-800 pb-2">
              <span className="flex items-center gap-1.5 font-bold text-craft-200">
                <Terminal className="w-3.5 h-3.5 text-craft-accent" />
                <span>Install ASL in 5 Seconds</span>
              </span>
              <span className="text-craft-500">macOS / Linux / Windows</span>
            </div>
            <div className="flex items-center justify-between gap-3 bg-craft-950 p-2.5 rounded-lg border border-craft-800">
              <code className="text-craft-accent select-all overflow-x-auto whitespace-nowrap">
                curl -fsSL https://aslang.dev/install.sh | bash
              </code>
              <button
                onClick={() => {
                  navigator.clipboard.writeText('curl -fsSL https://aslang.dev/install.sh | bash');
                  alert('Copied to clipboard: curl -fsSL https://aslang.dev/install.sh | bash');
                }}
                className="px-2.5 py-1 rounded bg-craft-800 hover:bg-craft-700 text-craft-200 text-[11px] transition-colors shrink-0"
              >
                Copy
              </button>
            </div>
            <div className="flex flex-wrap gap-3 mt-2 text-[10px] text-craft-400 font-mono pt-1">
              <span>Also via:</span>
              <span className="text-craft-300">brew install aslang</span>
              <span>•</span>
              <span className="text-craft-300">npx aslang init</span>
              <span>•</span>
              <span className="text-craft-300">pip install aslang</span>
            </div>
          </div>

          <div className="mt-6 flex flex-wrap gap-4 items-center font-mono">
            <a
              href="#eddie"
              className="px-5 py-3 rounded bg-craft-accent text-craft-950 font-semibold text-sm hover:bg-craft-accent/90 transition-all flex items-center gap-2 shadow-lg shadow-craft-accent/10"
            >
              <span>Explore EDDIE Swarm</span>
              <ArrowRight className="w-4 h-4" />
            </a>
            <a
              href="#skills"
              className="px-5 py-3 rounded bg-craft-900 border border-craft-700 text-craft-100 text-sm hover:border-craft-500 transition-colors flex items-center gap-2"
            >
              <Terminal className="w-4 h-4 text-craft-accent" />
              <span>Skills Hub & MCP</span>
            </a>
          </div>

          {/* Feature Highlights Grid */}
          <div className="mt-12 grid grid-cols-1 sm:grid-cols-3 gap-4 border-t border-craft-800/80 pt-8">
            <div className="p-4 rounded border border-craft-800 bg-craft-900/50">
              <div className="flex items-center gap-2 text-craft-accent font-mono text-sm font-semibold mb-1">
                <Cpu className="w-4 h-4" />
                <span>Pure Wasm Edge</span>
              </div>
              <p className="text-xs text-craft-400 font-mono">Instant in-browser WASI execution with memory isolation.</p>
            </div>

            <div className="p-4 rounded border border-craft-800 bg-craft-900/50">
              <div className="flex items-center gap-2 text-craft-accent font-mono text-sm font-semibold mb-1">
                <ShieldCheck className="w-4 h-4" />
                <span>100% Deterministic</span>
              </div>
              <p className="text-xs text-craft-400 font-mono">Exhaustive matching, effect tracking, zero unhandled errors.</p>
            </div>

            <div className="p-4 rounded border border-craft-800 bg-craft-900/50">
              <div className="flex items-center gap-2 text-craft-accent font-mono text-sm font-semibold mb-1">
                <Zap className="w-4 h-4" />
                <span>-78% Token Context</span>
              </div>
              <p className="text-xs text-craft-400 font-mono">Structured interface compressor saving LLM prompt budgets.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
