import React, { useState } from 'react';
import { Cpu, ShieldCheck, Zap, ArrowRight, Terminal, Check, Activity, Radio } from 'lucide-react';

export const Hero: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText('curl -fsSL https://aslang.dev/install.sh | bash');
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section className="relative pt-12 pb-24 border-b border-craft-200/80 dark:border-craft-800/80 bg-white dark:bg-craft-950 grid-mesh overflow-hidden transition-colors">
      {/* Background Cybernetic Glow Cones */}
      <div className="absolute top-0 right-1/4 w-[600px] h-[400px] bg-craft-accent/15 blur-[140px] rounded-full pointer-events-none" />
      <div className="absolute top-1/3 left-10 w-[400px] h-[300px] bg-purple-500/10 blur-[120px] rounded-full pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Main Grid: Left Hero Typography + Right Intertwined 3D Droid Node */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          {/* Left Column: Manifesto & Controls */}
          <div className="lg:col-span-7 space-y-6 text-left">
            {/* Live Telemetry Pill */}
            <div className="inline-flex items-center gap-2.5 px-3.5 py-1.5 rounded-full border border-craft-200 dark:border-craft-700/80 bg-craft-100/90 dark:bg-craft-900/90 backdrop-blur-xl text-xs font-mono text-craft-800 dark:text-craft-accent shadow-sm">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-craft-accent opacity-75" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-craft-accent" />
              </span>
              <span className="font-semibold tracking-wide">AUTONOMOUS SWARM RUNTIME // v1.0 NANO</span>
            </div>

            {/* Monumental Headline */}
            <h1 className="text-4xl sm:text-6xl lg:text-6xl font-extrabold tracking-tight font-sans leading-[1.08] text-craft-900 dark:text-craft-50">
              Code generated by Agents.{' '}
              <span className="block mt-2 bg-gradient-to-r from-craft-accent via-teal-400 to-emerald-400 bg-clip-text text-transparent">
                Executed at native speed.
              </span>
            </h1>

            {/* High-Impact Description */}
            <p className="text-base sm:text-lg text-craft-600 dark:text-craft-300 font-sans leading-relaxed max-w-xl">
              <strong>ASL Nano</strong> is the zero-overhead, agent-native programming language. Single-pass S-expressions, 0 syntax repair loops, <strong>78% lower prompt token overhead</strong>, and instant WebAssembly sandboxing in &lt;0.04ms.
            </p>

            {/* Fast-Track 1-Line Installer Card */}
            <div className="p-3 rounded-2xl border border-craft-200 dark:border-craft-800 bg-craft-50/90 dark:bg-craft-900/90 backdrop-blur-xl shadow-xl max-w-xl transition-all">
              <div className="flex items-center justify-between text-[11px] text-craft-500 dark:text-craft-400 mb-2 px-1 border-b border-craft-200 dark:border-craft-800/80 pb-2">
                <span className="flex items-center gap-1.5 font-bold font-mono text-craft-800 dark:text-craft-200">
                  <Terminal className="w-3.5 h-3.5 text-craft-accent" />
                  <span>Instant Installation</span>
                </span>
                <span className="font-mono text-craft-400 dark:text-craft-500 text-[10px]">macOS / Linux / WSL</span>
              </div>
              
              <div className="flex items-center justify-between gap-3 bg-white dark:bg-craft-950 px-3 py-2.5 rounded-xl border border-craft-200 dark:border-craft-800 shadow-inner">
                <code className="text-craft-900 dark:text-craft-accent font-mono text-xs sm:text-sm select-all overflow-x-auto whitespace-nowrap">
                  curl -fsSL https://aslang.dev/install.sh | bash
                </code>
                <button
                  onClick={handleCopy}
                  className="px-3 py-1.5 rounded-lg bg-craft-200 dark:bg-craft-800 hover:bg-craft-300 dark:hover:bg-craft-700 text-craft-800 dark:text-craft-100 font-mono text-xs transition-all flex items-center gap-1.5 shrink-0"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-craft-emerald" />
                      <span className="text-craft-emerald">Copied!</span>
                    </>
                  ) : (
                    <span>Copy</span>
                  )}
                </button>
              </div>
            </div>

            {/* Primary Action Buttons */}
            <div className="flex flex-wrap gap-4 items-center font-mono pt-2">
              <a
                href="#eddie"
                className="px-6 py-3.5 rounded-xl bg-craft-accent text-craft-950 font-bold text-sm hover:bg-craft-accent/90 hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center gap-2 shadow-glow-md"
              >
                <span>Launch EDDIE Swarm</span>
                <ArrowRight className="w-4 h-4" />
              </a>
              <a
                href="#skills"
                className="px-6 py-3.5 rounded-xl bg-craft-100 dark:bg-craft-900 border border-craft-200 dark:border-craft-700/80 text-craft-800 dark:text-craft-100 text-sm hover:border-craft-accent hover:text-craft-accent transition-all flex items-center gap-2"
              >
                <Terminal className="w-4 h-4 text-craft-accent" />
                <span>Skills Hub & MCP</span>
              </a>
            </div>
          </div>

          {/* Right Column: Intertwined 3D Droid Core Node & Live Telemetry Glass HUD */}
          <div className="lg:col-span-5 relative">
            {/* The 3D Cybernetic Droid Core Image with Overlapping HUD */}
            <div className="relative rounded-2xl border border-craft-200 dark:border-craft-800/90 bg-craft-100/40 dark:bg-craft-900/60 p-3 backdrop-blur-2xl shadow-2xl overflow-hidden group">
              <img
                src="/assets/images/hero_droid.jpg"
                alt="Autonomous AI Droid Core"
                className="w-full h-auto rounded-xl object-cover shadow-inner group-hover:scale-105 transition-transform duration-700"
              />

              {/* Floating Glass Telemetry Badges (Overlapping) */}
              <div className="absolute top-6 left-6 p-3 rounded-xl bg-white/85 dark:bg-craft-950/85 backdrop-blur-xl border border-craft-200/80 dark:border-craft-700/80 shadow-lg text-left font-mono">
                <div className="flex items-center gap-2 text-[10px] text-craft-accent font-bold">
                  <Activity className="w-3.5 h-3.5 animate-pulse text-craft-emerald" />
                  <span>AI DROID UNIT-7</span>
                </div>
                <div className="text-[11px] text-craft-800 dark:text-craft-200 font-semibold mt-0.5">
                  WASM ISOLATE: ACTIVE
                </div>
                <div className="text-[9px] text-craft-500 dark:text-craft-400">LATENCY: 0.038ms</div>
              </div>

              <div className="absolute bottom-6 right-6 p-3 rounded-xl bg-white/85 dark:bg-craft-950/85 backdrop-blur-xl border border-craft-200/80 dark:border-craft-700/80 shadow-lg text-right font-mono">
                <div className="flex items-center justify-end gap-1.5 text-[10px] text-craft-accent font-bold">
                  <Radio className="w-3.5 h-3.5 text-craft-cyan animate-pulse" />
                  <span>SWARM BUS: SSE</span>
                </div>
                <div className="text-[11px] text-craft-800 dark:text-craft-200 font-semibold mt-0.5">
                  107 BUILTINS READY
                </div>
                <div className="text-[9px] text-craft-emerald font-medium">100% SPEC VERIFIED</div>
              </div>
            </div>

            {/* Glowing Accent Ring */}
            <div className="absolute -bottom-6 -right-6 w-32 h-32 bg-craft-accent/20 blur-3xl rounded-full pointer-events-none" />
          </div>

        </div>

        {/* Feature Highlights Grid */}
        <div className="mt-16 grid grid-cols-1 sm:grid-cols-3 gap-6 text-left">
          <div className="p-6 rounded-2xl border border-craft-200 dark:border-craft-800/80 bg-craft-50/60 dark:bg-craft-900/40 backdrop-blur-md hover:border-craft-accent/50 hover:shadow-glow-sm transition-all group">
            <div className="flex items-center gap-3 text-craft-accent font-mono text-sm font-semibold mb-2">
              <div className="p-2.5 rounded-xl bg-white dark:bg-craft-950 border border-craft-200 dark:border-craft-800 group-hover:scale-110 transition-transform">
                <Cpu className="w-4 h-4 text-craft-accent" />
              </div>
              <span>Pure Wasm Edge</span>
            </div>
            <p className="text-xs sm:text-sm text-craft-600 dark:text-craft-300 font-sans leading-relaxed">
              In-memory WASI preview1 execution with zero-cost memory isolation in under <strong>0.038ms</strong>.
            </p>
          </div>

          <div className="p-6 rounded-2xl border border-craft-200 dark:border-craft-800/80 bg-craft-50/60 dark:bg-craft-900/40 backdrop-blur-md hover:border-craft-accent/50 hover:shadow-glow-sm transition-all group">
            <div className="flex items-center gap-3 text-craft-accent font-mono text-sm font-semibold mb-2">
              <div className="p-2.5 rounded-xl bg-white dark:bg-craft-950 border border-craft-200 dark:border-craft-800 group-hover:scale-110 transition-transform">
                <ShieldCheck className="w-4 h-4 text-craft-emerald" />
              </div>
              <span>100% Deterministic</span>
            </div>
            <p className="text-xs sm:text-sm text-craft-600 dark:text-craft-300 font-sans leading-relaxed">
              Exhaustive pattern matching and static effect tracking eliminate all runtime undefined errors.
            </p>
          </div>

          <div className="p-6 rounded-2xl border border-craft-200 dark:border-craft-800/80 bg-craft-50/60 dark:bg-craft-900/40 backdrop-blur-md hover:border-craft-accent/50 hover:shadow-glow-sm transition-all group">
            <div className="flex items-center gap-3 text-craft-accent font-mono text-sm font-semibold mb-2">
              <div className="p-2.5 rounded-xl bg-white dark:bg-craft-950 border border-craft-200 dark:border-craft-800 group-hover:scale-110 transition-transform">
                <Zap className="w-4 h-4 text-amber-500" />
              </div>
              <span>-78% Token Context</span>
            </div>
            <p className="text-xs sm:text-sm text-craft-600 dark:text-craft-300 font-sans leading-relaxed">
              ASL Nano interface compression dramatically reduces multi-agent LLM inference costs.
            </p>
          </div>
        </div>

      </div>
    </section>
  );
};
